# Setup
title:               Dorktips
tagline:             'Dork it up'
description:         'Tips, tricks and tools for software dorks.'
url:                 'https://nsbruce.github.io/dork-tips/'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nicholas Bruce
  url:               https://github.com/nsbruce
  email:             nicholas@nicholasbruce.ca

github:
  repo: https://github.com/nsbruce/dork-tips

# Gems
plugins:
  - jekyll-paginate

